# Generated by Django 3.0.8 on 2020-09-29 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile-pic-default.jpg', upload_to='profile_pics')),
                ('banner_image', models.ImageField(default='slider-1.jpg', upload_to='banner')),
                ('job_title', models.CharField(max_length=100)),
                ('bio', tinymce.models.HTMLField()),
                ('date_birth', models.DateField(default='1999-12-31')),
                ('gender', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=128, verbose_name='Genero')),
                ('country', models.CharField(help_text='Indique su país', max_length=100)),
                ('twitter_url', models.CharField(blank=True, default='#', help_text='Ingrese # si no tiene una cuenta', max_length=250, null=True)),
                ('instagram_url', models.CharField(blank=True, default='#', help_text='Ingrese # si no tiene una cuenta', max_length=250, null=True)),
                ('facebook_url', models.CharField(blank=True, default='#', help_text='Ingrese # si no tiene una cuenta', max_length=250, null=True)),
                ('github_url', models.CharField(blank=True, default='#', help_text='Ingrese # si no tiene una cuenta', max_length=250, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
